name: PHPCS

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'renovate/**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:458ceee0d7746e8c0c7241f73cd3cf49cd7e114398017d857e86cee1c635ff4c
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPCS
        run: composer phpcs
