name: PHPCS

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'renovate/**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:78e4d168f77d3433fd23d828af674435fc8d9048bfc12c9abd63d7b2b5d38a9d
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPCS
        run: composer phpcs
