name: PHPStan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:86c5e2d20be573eca54b2d03479f6ec8133c4bbdf1ac7fb2d8f19f6a3ad1ea1e
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:86c5e2d20be573eca54b2d03479f6ec8133c4bbdf1ac7fb2d8f19f6a3ad1ea1e
        with:
          args: analyze --error-format=table /github/workspace
