name: PHPUnit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'renovate/**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:ed418fc0d727187812a62237f76cfba7a24d9f5a4a30b6d4b417828c44fffc34
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Composer
        run: composer install

      - name: PHPUnit
        run: composer unittest
